const Constants = {
  CharacterCodes: [
    "FEMALE_10",
    "FEMALE_09",
    "FEMALE_08",
    "FEMALE_07",
    "FEMALE_06",
    "FEMALE_05",
    "FEMALE_04",
    "FEMALE_03",
    "FEMALE_02",
  ],
  DanceAnim: [
    "capoeira",
    "chicken_dance",
    "falling",
    "flair",
    "gangnam_style",
    "hiphop",
    "punch",
  ],
  AnimClipModel: [
    { name: "idle" },
    { name: "run_backward" },
    { name: "run_forward" },
    { name: "run_left" },
    { name: "run_right" },
    { name: "capoeira" },
    { name: "chicken_dance" },
    { name: "falling" },
    { name: "flair" },
    { name: "gangnam_style" },
    { name: "hiphop" },
    { name: "ninja_idle" },
    { name: "punch", timeScale: 2 },
  ],
};
export default Constants;
