import { LoopOnce, LoopPingPong, Vector2, Vector3 } from "three";

const Constants: any = {
  CharacterCodes: [
    "FEMALE_02",
    "FEMALE_10",
    "FEMALE_09",
    "FEMALE_08",
    "FEMALE_07",
    "FEMALE_06",
    "FEMALE_05",
    "FEMALE_04",
    "FEMALE_03",
    "FEMALE_01",
    "MALE_10",
    "MALE_09",
    "MALE_08",
    "MALE_07",
    "MALE_06",
    "MALE_05",
    "MALE_04",
    "MALE_03",
    "MALE_02",
    "MALE_01",
    "BASIC_01",
    "BASIC_02",
    "BASIC_03",
  ],
  CharacterData: {
    MALE_MONSTERRA: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_10: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_09: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_08: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_07: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_06: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_05: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_04: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_03: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_02: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    MALE_01: {
      model: "model_male_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    BASIC_01: {
      model: "model_basic",
      anim_top: "basic_anim_top",
      anim_bottom: "basic_anim_bottom",
      scale: new Vector3(0.015, 0.015, 0.015),
    },
    BASIC_02: {
      model: "model_basic",
      anim_top: "basic_anim_top",
      anim_bottom: "basic_anim_bottom",
      scale: new Vector3(0.015, 0.015, 0.015),
    },
    BASIC_MONSTERRA: {
      model: "model_basic",
      anim_top: "basic_anim_top",
      anim_bottom: "basic_anim_bottom",
      scale: new Vector3(0.015, 0.015, 0.015),
    },
    BASIC_GUEST: {
      model: "model_basic",
      anim_top: "basic_anim_top",
      anim_bottom: "basic_anim_bottom",
      scale: new Vector3(0.015, 0.015, 0.015),
    },
    BASIC_03: {
      model: "model_basic",
      anim_top: "basic_anim_top",
      anim_bottom: "basic_anim_bottom",
      scale: new Vector3(0.015, 0.015, 0.015),
    },
    FEMALE_10: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    FEMALE_09: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    FEMALE_08: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    FEMALE_07: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    FEMALE_06: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    FEMALE_05: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    FEMALE_04: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    FEMALE_03: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    FEMALE_02: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
    FEMALE_01: {
      model: "model_female_premium",
      anim_top: "female_anim_top",
      anim_bottom: "female_anim_bottom",
      scale: new Vector3(0.1, 0.1, 0.1),
    },
  },
  // right - bottom - left - top
  DanceAnim: [
    {
      anim: "capoeira",
      name: "Capoeira",
    },
    {
      anim: "chicken_dance",
      name: "Chicken Dance",
    },
    {
      anim: "flair",
      name: "Flair",
    },
    {
      anim: "gangnam_style",
      name: "Gangnam Style",
    },
    {
      anim: "hiphop",
      name: "Hiphop",
    },
  ],
  AnimClipModel: [
    { name: "idle" },
    { name: "run_backward" },
    { name: "run_forward" },
    { name: "run_left" },
    { name: "run_right" },
    { name: "walking_backward" },
    { name: "walking_forward" },
    { name: "walking_left" },
    { name: "walking_right" },
    { name: "capoeira" },
    { name: "chicken_dance" },
    { name: "flair" },
    { name: "gangnam_style" },
    { name: "hiphop" },
    { name: "ninja_idle" },
    { name: "punch", timeScale: 2, loop: LoopPingPong, repetitions: 1.1 },
    { name: "fall_idle", timeScale: 1.5 },
    { name: "fall_to_landing", timeScale: 1, loop: LoopOnce },
    { name: "die", timeScale: 1.2 },
    { name: "stand", timeScale: 2, loop: LoopOnce },
  ],
  SkinAvatarImgs: {
    FEMALE_02: "ui/Female/2.png",
    FEMALE_10: "ui/Female/10.png",
    FEMALE_09: "ui/Female/9.png",
    FEMALE_08: "ui/Female/8.png",
    FEMALE_07: "ui/Female/7.png",
    FEMALE_06: "ui/Female/6.png",
    FEMALE_05: "ui/Female/5.png",
    FEMALE_04: "ui/Female/4.png",
    FEMALE_03: "ui/Female/3.png",
    FEMALE_01: "ui/Female/1.png",
    MALE_10: "ui/Male/10.png",
    MALE_09: "ui/Male/9.png",
    MALE_08: "ui/Male/8.png",
    MALE_07: "ui/Male/7.png",
    MALE_06: "ui/Male/6.png",
    MALE_05: "ui/Male/5.png",
    MALE_04: "ui/Male/4.png",
    MALE_03: "ui/Male/3.png",
    MALE_02: "ui/Male/2.png",
    MALE_01: "ui/Male/1.png",
    BASIC_01: "ui/Basic/Basic1.png",
    BASIC_02: "ui/Basic/Basic2.png",
    BASIC_03: "ui/Basic/Basic3.png",
  },
};
export default Constants;
